services:
  frontend:
    image: vsd2107/arcis_frontend_R-D:latest
    env_file:
      - ./frontend/.env
    ports:
      - "80:80"

  backend:
    image: vsd2107/arcis_backend_R-D:latest
    env_file:
      - ./backend/.config.env
    ports:
      - "8082:8082"